<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4aFtmWw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4aFtmWw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4aFtmWw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4aFtmWw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4aFtmWw\App_KernelDevDebugContainer([
    'container.build_hash' => '4aFtmWw',
    'container.build_id' => '9ee113f2',
    'container.build_time' => 1584450477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4aFtmWw');
