<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFR1clz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFR1clz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFR1clz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFR1clz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFR1clz\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFR1clz',
    'container.build_id' => '647444a8',
    'container.build_time' => 1584528390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFR1clz');
