<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuBFZW0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuBFZW0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuBFZW0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuBFZW0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWuBFZW0\App_KernelDevDebugContainer([
    'container.build_hash' => 'WuBFZW0',
    'container.build_id' => '3c245f31',
    'container.build_time' => 1584533077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuBFZW0');
